# Generated by Django 5.0 on 2023-12-24 20:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=64)),
                ('owner', models.CharField(max_length=64)),
                ('platform', models.CharField(max_length=64)),
                ('link', models.URLField()),
                ('thumbnail', models.ImageField(blank=True, upload_to='playlist_history/thumbnails')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('artist', models.CharField(max_length=64)),
                ('playlist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='songs', to='app.playlist')),
            ],
        ),
    ]
