# Generated by Django 5.0 on 2024-01-02 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='owner',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='playlist',
            name='platform',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='track',
            name='artist',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='track',
            name='id',
            field=models.CharField(max_length=128, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='track',
            name='name',
            field=models.CharField(max_length=128),
        ),
        migrations.AlterField(
            model_name='track',
            name='platform',
            field=models.CharField(max_length=128),
        ),
    ]
