# Generated by Django 5.0.4 on 2024-04-28 14:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Track",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=128)),
                ("artist", models.CharField(max_length=128)),
                ("platform", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="Playlist",
            fields=[
                (
                    "id",
                    models.CharField(max_length=128, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=128)),
                ("owner", models.CharField(max_length=128)),
                ("platform", models.CharField(max_length=128)),
                ("thumbnail", models.URLField(blank=True)),
                ("last_modified", models.DateTimeField(auto_now=True)),
                (
                    "watcher",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tracks",
                    models.ManyToManyField(related_name="playlists", to="server.track"),
                ),
            ],
        ),
    ]
